images:
  airflow:
    repository: irvingfgr/airflow-deb # Your Docker Hub repo and image name
    tag: 0.0.2 # The tag you chose when building the Dockerfile

logs:
  persistence:
    # Enable persistent volume for storing logs
    enabled: true
    # Volume size for logs
    size: 1Gi
    # If using a custom storageClass, pass name here
    storageClassName: nfs-client

## Git sync
#dags:
#  persistence:
#    # Enable persistent volume for storing dags
#    enabled: true
#    # Volume size for dags
#    size: 1Gi
#    # If using a custom storageClass, pass name here
#    storageClassName: nfs-client
#    # access mode of the persistent volume
#    accessMode: ReadWriteMany
#
#  gitSync:
#    enabled: true
#    repo: https://github.com/IrvingFGalRam/airflow-dags
#    branch: main
#    rev: HEAD
#    depth: 1
#    # the number of consecutive failures allowed before aborting
#    maxFailures: 0
#    # subpath within the repo where dags are located
#    # should be "" if dags are at repo root
#    subPath: ""
#
#
#logs:
#  persistence:
#    # Enable persistent volume for storing logs
#    enabled: true
#    # Volume size for logs
#    size: 1Gi
#    # If using a custom storageClass, pass name here
#    storageClassName: nfs-client